version: '3.4'
services:
  nginx:
    ports:
    - "8080:8080"
  netbox:
    image: netboxcommunity/netbox:${VERSION-latest-ldap}
    environment:
      AUTH_LDAP_SERVER_URI: "ldaps://domain.com"
      AUTH_LDAP_BIND_DN: "CN=Netbox,OU=BindUsers,OU=Company,DC=domain,dc=com"
      AUTH_LDAP_BIND_PASSWORD: "BindPassword"
      AUTH_LDAP_USER_SEARCH_BASEDN: "OU=Users,OU=Company,DC=domain,dc=com"
      AUTH_LDAP_GROUP_SEARCH_BASEDN: "OU=Groups,OU=Company,DC=domain,dc=com"
      AUTH_LDAP_REQUIRE_GROUP_DN: "CN=Netbox-User,OU=SoftwareGroups,OU=SubGroups,OU=MyCompany,DC=domain,dc=com"
      AUTH_LDAP_IS_ADMIN_DN: "CN=Network Admins,OU=Groups,OU=MyCompany,DC=domain,dc=com"
      AUTH_LDAP_IS_SUPERUSER_DN: "CN=Domain Admins,CN=Users,DC=domain,dc=com"
      LDAP_IGNORE_CERT_ERRORS: "true"
  tls:
    image: zazukoians/hitch
    environment:
      HITCH_PEM: /app/localhost.pem
      HITCH_PARAMS: --backend=[nginx]:8080 --frontend=[*]:443
    volumes:
      - "./localhost+2-full.pem:/app/localhost.pem"
    ports:
      - "443:443"
    depends_on:
      - nginx
